# Generated by Django 3.0.4 on 2020-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='categories',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='executionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='income',
            name='executionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.FloatField(default='0'),
        ),
    ]
